# version format
version: 0.1.{build}

#clone_folder: /appveyor/projects/src/godatastruct

# branches to build
branches:
  # whitelist
  only:
    - develop
    - master

# Do not build on tags (GitHub only)
skip_tags: true

install:
  - export APR_HOME=/usr/local/apr/


build_cloud: EGOROFF Docker
image: Ubuntu



