name: Windows Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: Create generated dir
      run: |
        mkdir ${{ github.workspace }}/src/grok/generated
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      uses: lukka/run-cmake@v2
      with:
        cmakeGenerator: VS16Win64
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        cmakeBuildType: Release
        buildWithCMakeArgs: "-- -m"
        buildDirectory: ${{ runner.temp }}/build
        buildWithCMake: true
    - name: Install
      run: |
        cmake --install ${{ runner.temp }}/build
    - uses: actions/upload-artifact@v2
      with:
        name: grok
        path: ${{ github.workspace }}/bin/*.*
