name: Windows Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        cmakeBuildType: Release
        buildWithCMakeArgs: "--config Release -- -m"
        buildDirectory: ${{ runner.temp }}/build
        buildWithCMake: true
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G"Visual Studio 16 2019" -Ax64'
    - name: Install
      run: |
        cmake --install ${{ runner.temp }}/build
    - uses: actions/upload-artifact@v2
      with:
        name: grok
        path: ${{ github.workspace }}/bin/*.*
