name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: flex
      run: "$(GnuBasePath)/win_flex.exe --wincompat --outfile=src/grok/grok.flex.c src/grok/grok.lex"
    - name: bison
      run: "$(GnuBasePath)/win_bison.exe --output=src/grok/grok.tab.c -dy src/grok/grok.y"
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: lukka/run-cmake@v1
      with:
        cmakeGenerator: VS16Win64
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        cmakeBuildType: Release
        buildWithCMakeArgs: "--config Release -- -v:quiet -m"
        buildDirectory: ${{ runner.temp }}/build
        buildWithCMake: true
