name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: "C:/Program Files/CMake/bin/cmake.exe" "-DCMAKE_BUILD_TYPE=Release" "-G" "CodeBlocks - NMake Makefiles" grok
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
